import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0d0d0d',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  imagen: {
    width: 240,
    height: 120,
    marginBottom: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#444',
    shadowColor: '#00ffcc',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
    backgroundColor: '#1a1a1a',
  },
  textInput: {
    width: '100%',
    borderColor: '#555',
    borderWidth: 1.5,
    borderRadius: 15,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 12,
    backgroundColor: '#1a1a1a',
    fontSize: 18,
    color: '#ffffff',
    shadowColor: '#00ffcc',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  button: {
    backgroundColor: '#00cc99',
    paddingVertical: 18,
    paddingHorizontal: 50,
    borderRadius: 30,
    marginTop: 25,
    shadowColor: '#00ffcc',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 10,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  title: {
    fontSize: 36,
    fontWeight: '900',
    color: '#00cc99',
    marginBottom: 25,
    textAlign: 'center',
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 255, 204, 0.4)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 12,
  },
  headerText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 20,
    textAlign: 'center',
  },
  texto2: {
    color: '#b3b3b3',
    textAlign: 'center',
    marginBottom: 20,
    marginHorizontal: 15,
    fontSize: 15,
    lineHeight: 24,
  },
});
